version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "[dependencies]"

    cooldown:
      default-days: 8
      semver-major-days: 15
      semver-minor-days: 10
      semver-patch-days: 8
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns: ["*"]
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
